copied trail project and fixed the lint errors
ayebaishmo/review_trail_project pull request #1
Opened 2021-06-02 20:35 UTC by ayebaishmo

Copied my trial project.
Used npm to add node modules in order to  fix the lint errors for HTML and CSS.
Deleted unnecessary JavaScript files and codes

2021-06-02 20:55 UTC, ayebaishmo reviewed
Hey
@ayebaishmo great work done so far
I reviewed your repository:  
**REQUIRED CHANGES** 

1. Read me file shows nothing yet it should be descriptive, in other words "tells more about the project"
2. Best to start your commit messages with capital letter
3. There is empty JavaScript filest in the repository

2021-06-03 01:23 UTC, Spayco requested changes
Hi @ayebaishmo, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

Your review could use some improvements, please create a new one and double-check that you're following this list:
- GitHub features
  - it's best to utilize the "Review changes" feature from GitHub
  - (from the lesson page) it's required to find at least 2 issues in the code
  - please include those changes using [inline comments](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request)
- Communication: 
  - kindly phrase the comments politely, as suggestions instead of orders. For example:
     * This is a polite suggestion: *"I think it would be better to use semantic tags"*
     * This reads as an order: *"Use semantic tags"*
  - please always include an explanation, a "why", for each requested change. For example:
     * This is a well explained request: *Why don't you use an article tag for the .first-article element instead of a div, that would improve the HTML structure and make the page more accessible*
     * This request lacks a "why": *Why don't you use an article tag here instead of a div?*
  
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-03 10:16 UTC, ayebaishmo reviewed
Hey @ayebaishmo so far so good

**CHANGES REQUIRED**

-

2021-06-03 10:16 UTC, ayebaishmo commented on style.css
> +ul {
Hey @ayebaishmo 
I think it would  be better to use two spaces for indentation in css, It makes the code look smart and easy for reviewing

2021-06-03 10:16 UTC, ayebaishmo commented on index.html
> +        <h1 id="title">Dr. Norman Borlaug</h1>
I also think it would be better to use two white spaces for it enables easy navigation and readability for the code in html

2021-06-03 12:34 UTC, Spayco approved these changes
Hi @ayebaishmo, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-03 13:05 UTC, merged